local config = { 
	[1] = { 
		id = 1,
		content = "人名显示",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "人名显示",
		default = 1,
		platform = 0,
		order = 100,
	},
	[2] = { 
		id = 2,
		content = "数字显血",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "数字显血",
		default = 1,
		platform = 0,
		order = 200,
	},
	[3] = { 
		id = 3,
		content = "数字飘血",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "数字飘血",
		default = 1,
		platform = 0,
		order = 300,
	},
	[4] = { 
		id = 4,
		content = "显示血条",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "显示血条",
		default = 1,
		platform = 0,
		order = 400,
	},
	[5] = { 
		id = 5,
		content = "怪物显名",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "怪物显名",
		default = 1,
		platform = 0,
		order = 500,
	},
	[6] = { 
		id = 6,
		content = "单双摇杆",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "单双摇杆",
		default = 1,
		platform = 2,
		order = 3550,
	},
	[7] = { 
		id = 7,
		content = "生命值低于<font colorStyleID='1040006'>%s%%</font> 自动使用回城卷",
		text = "保护-回城",
		group = 2,
		group2 = 1,
		group_text = "保护设置",
		default = 0,
		platform = 0,
		order = 600,
		default1 = 80,
	},
	[8] = { 
		id = 8,
		content = "生命值低于<font colorStyleID='1040006'>%s%%</font> 自动使用随机卷",
		text = "保护-随机",
		group = 2,
		group2 = 1,
		group_text = "保护设置",
		default = 0,
		platform = 0,
		order = 650,
	},
	[77] = { 
		id = 77,
		content = "魔法值低于<font colorStyleID='1040006'>%s%%</font> 自动使用回城卷",
		text = "保护-回城",
		group = 2,
		group2 = 1,
		group_text = "保护设置",
		default = 0,
		platform = 0,
		order = 680,
	},
	[88] = { 
		id = 88,
		content = "魔法值低于<font colorStyleID='1040006'>%s%%</font> 自动使用随机卷",
		text = "保护-随机",
		group = 2,
		group2 = 1,
		group_text = "保护设置",
		default = 0,
		platform = 0,
		order = 690,
	},
	[9] = { 
		id = 9,
		content = "生命值低于<font colorStyleID='1040006'>%s%%</font> 自动使用红药HP",
		text = "普通恢复HP",
		group = 2,
		group2 = 1,
		group_text = "保护设置",
		default = 1,
		platform = 0,
		order = 700,
	},
	[10] = { 
		id = 10,
		content = "生命值低于<font colorStyleID='1040006'>%s%%</font> 自动使用瞬回药",
		text = "瞬回恢复HP",
		group = 2,
		group2 = 1,
		group_text = "保护设置",
		default = 1,
		platform = 0,
		order = 750,
	},
	[11] = { 
		id = 11,
		content = "魔法值低于<font colorStyleID='1040006'>%s%%</font> 自动使用蓝药MP",
		text = "普通恢复MP",
		group = 2,
		group2 = 1,
		group_text = "保护设置",
		default = 1,
		platform = 0,
		order = 760,
	},
	[12] = { 
		id = 12,
		content = "魔法值低于<font colorStyleID='1040006'>%s%%</font> 自动使用瞬回药",
		text = "瞬回恢复MP",
		group = 2,
		group2 = 1,
		group_text = "保护设置",
		default = 1,
		platform = 0,
		order = 770,
	},
	[13] = { 
		id = 13,
		content = "自动走位",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 0,
		platform = 0,
		order = 1200,
	},
	[14] = { 
		id = 14,
		content = "持续攻击",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 1,
		platform = 2,
		order = 1300,
	},
	[15] = { 
		id = 15,
		content = "刀刀刺杀",
		text = "战斗",
		group = 3,
		group2 = 2,
		group_text = "战士",
		default = 1,
		platform = 0,
		order = 1400,
	},
	[16] = { 
		id = 16,
		content = "自动烈火剑法",
		text = "战斗",
		group = 3,
		group2 = 2,
		group_text = "战士",
		default = 1,
		platform = 0,
		order = 1500,
	},
	[17] = { 
		id = 17,
		content = "隔位刺杀",
		text = "战斗",
		group = 3,
		group2 = 2,
		group_text = "战士",
		default = 1,
		platform = 1,
		order = 1600,
	},
	[18] = { 
		id = 18,
		content = "智能半月",
		text = "战斗",
		group = 3,
		group2 = 2,
		group_text = "战士",
		default = 1,
		platform = 0,
		order = 1700,
	},
	[19] = { 
		id = 19,
		content = "自动魔法盾",
		text = "战斗",
		group = 3,
		group2 = 3,
		group_text = "法师",
		default = 1,
		platform = 0,
		order = 1800,
	},
	[20] = { 
		id = 20,
		content = "自动火墙",
		text = "战斗",
		group = 3,
		group2 = 3,
		group_text = "法师",
		default = 1,
		platform = 0,
		order = 1900,
	},
	[21] = { 
		id = 21,
		content = "群怪技能",
		text = "战斗",
		group = 3,
		group2 = 3,
		group_text = "法师",
		default = 0,
		platform = 0,
		order = 2000,
	},
	[22] = { 
		id = 22,
		content = "自动施毒",
		text = "战斗",
		group = 3,
		group2 = 4,
		group_text = "道士",
		default = 0,
		platform = 0,
		order = 2100,
	},
	[23] = { 
		id = 23,
		content = "自动幽灵盾",
		text = "战斗",
		group = 3,
		group2 = 4,
		group_text = "道士",
		default = 1,
		platform = 0,
		order = 2200,
	},
	[24] = { 
		id = 24,
		content = "自动神圣战甲术",
		text = "战斗",
		group = 3,
		group2 = 4,
		group_text = "道士",
		default = 1,
		platform = 0,
		order = 2300,
	},
	[25] = { 
		id = 25,
		content = "生命值低于<font colorStyleID='1040006'>%s%%</font> 时使用",
		text = "战斗",
		group = 3,
		group2 = 4,
		group_text = "道士",
		default = 0,
		platform = 0,
		order = 2400,
	},
	[26] = { 
		id = 26,
		content = "自动召唤",
		text = "战斗",
		group = 3,
		group2 = 4,
		group_text = "道士",
		default = 0,
		platform = 0,
		order = 2500,
	},
	[27] = { 
		id = 27,
		content = "背景音乐",
		text = "操作",
		group = 4,
		group2 = 1,
		group_text = "背景音乐",
		default = 100,
		platform = 0,
		order = 2600,
	},
	[28] = { 
		id = 28,
		content = "残血提示",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "残血提示",
		default = 1,
		platform = 0,
		order = 2700,
	},
	[29] = { 
		id = 29,
		content = "地图缩放",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "地图缩放",
		default = 1,
		platform = 2,
		order = 2800,
		default1 = 1.1,
	},
	[30] = { 
		id = 30,
		content = "技能接平砍",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 0,
		platform = 0,
		order = 2900,
	},
	[31] = { 
		id = 31,
		content = "免Shift",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 1,
		platform = 1,
		order = 3000,
	},
	[32] = { 
		id = 32,
		content = "平滑模式",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "平滑模式",
		default = 1,
		platform = 1,
		order = 3100,
	},
	[0] = { 
		id = 0,
		content = "只显人名",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "只显人名",
		default = 0,
		platform = 0,
		order = 150,
	},
	[34] = { 
		id = 34,
		content = "职业等级",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "职业等级",
		default = 1,
		platform = 0,
		order = 3300,
	},
	[35] = { 
		id = 35,
		content = "经验过滤",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "经验过滤",
		default = 0,
		platform = 0,
		order = 3400,
	},
	[36] = { 
		id = 36,
		content = "装备比较",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "装备比较",
		default = 1,
		platform = 0,
		order = 3500,
	},
	[37] = { 
		id = 37,
		content = "魔法锁定",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "魔法锁定",
		default = 1,
		platform = 0,
		order = 3600,
	},
	[38] = { 
		id = 38,
		content = "自动练功",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "自动练功",
		default = 0,
		platform = 0,
		order = 3800,
	},
	[39] = { 
		id = 39,
		content = "清理尸体",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "清理尸体",
		default = 1,
		platform = 0,
		order = 3700,
	},
	[40] = { 
		id = 40,
		content = "毒符互换",
		text = "战斗",
		group = 3,
		group2 = 4,
		group_text = "道士",
		default = 1,
		platform = 0,
		order = 2099,
	},
	[41] = { 
		id = 41,
		content = "宝宝跟随攻击",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 1,
		platform = 0,
		order = 3760,
		MainPos = "103#900#500#3|103#150#150#3",
		MainImg = "private/main/Target/1900012536.png",
		tips = "宝宝跟随主人一起攻击",
	},
	[42] = { 
		id = 42,
		content = "近身烈火",
		text = "战斗",
		group = 3,
		group2 = 2,
		group_text = "战士",
		default = 1,
		platform = 0,
		order = 1860,
	},
	[46] = { 
		id = 46,
		content = "BOSS提示",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "BOSS提示",
		default = 0,
		platform = 1,
		order = 4500,
	},
	[47] = { 
		id = 47,
		content = "单体技能",
		text = "战斗",
		group = 3,
		group2 = 3,
		group_text = "单体技能",
		default = 0,
		platform = 0,
		order = 2050,
	},
	[50] = { 
		id = 50,
		content = "持久提示",
		text = "战斗",
		group = 4,
		group2 = 1,
		group_text = "持久提示",
		default = 1,
		platform = 0,
		order = 3550,
	},
	[51] = { 
		id = 51,
		content = "自动修理",
		text = "战斗",
		group = 4,
		group2 = 1,
		group_text = "持久提示",
		default = 1,
		platform = 0,
		order = 4550,
	},
	[52] = { 
		id = 52,
		content = "游戏音乐",
		text = "操作",
		group = 4,
		group2 = 1,
		group_text = "游戏音乐",
		default = 100,
		platform = 0,
		order = 2650,
	},
	[53] = { 
		id = 53,
		content = "自动开天斩",
		text = "战斗",
		group = 3,
		group2 = 2,
		group_text = "战士",
		default = 1,
		platform = 0,
		order = 1750,
	},
	[54] = { 
		id = 54,
		content = "自动逐日剑法",
		text = "战斗",
		group = 3,
		group2 = 2,
		group_text = "战士",
		default = 1,
		platform = 0,
		order = 1760,
	},
	[55] = { 
		id = 55,
		content = "自动隐身",
		text = "战斗",
		group = 3,
		group2 = 4,
		group_text = "道士",
		default = 0,
		platform = 0,
		order = 2150,
	},
	[56] = { 
		id = 56,
		content = "移动隔位刺杀",
		text = "战斗",
		group = 3,
		group2 = 2,
		group_text = "战士",
		default = 0,
		platform = 2,
		order = 1600,
	},
	[57] = { 
		id = 57,
		content = "人物简装",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "人物简装",
		default = 0,
		platform = 0,
		order = 4560,
	},
	[58] = { 
		id = 58,
		content = "怪物简装",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "怪物简装",
		default = 0,
		platform = 0,
		order = 4570,
	},
	[59] = { 
		id = 59,
		content = "自动无极真气",
		text = "战斗",
		group = 3,
		group2 = 4,
		group_text = "道士",
		default = 0,
		platform = 0,
		order = 2350,
	},
	[60] = { 
		id = 60,
		content = "摇杆取消攻击",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "摇杆取消攻击",
		default = 1,
		platform = 2,
		order = 3550,
	},
	[61] = { 
		id = 61,
		content = "隐藏称号",
		text = "基本",
		group = 3,
		group2 = 1,
		group_text = "隐藏称号",
		default = 0,
		platform = 0,
		order = 2950,
	},
	[62] = { 
		id = 62,
		content = "自动穿装备",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "自动穿装备",
		default = 1,
		platform = 0,
		order = 2360,
	},
	[63] = { 
		id = 63,
		content = "人物低于55级不显示名称",
		text = "基本",
		group = 4,
		group2 = 1,
		group_text = "人物低于55级不显示名称",
		default = 0,
		platform = 0,
		order = 4580,
		default1 = 55,
		tips = "人物低于55级不显示角色名字\\鼠标点击角色才会显示",
	},
	[64] = { 
		id = 64,
		content = "自动反击",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "自动反击",
		default = 0,
		platform = 0,
		order = 3650,
		tips = "挂机时候自动反击攻击你的玩家",
	},
	[1002] = { 
		id = 1002,
		content = "高帧率模式",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 1,
		platform = 2,
		order = 1110,
	},
	[2001] = { 
		id = 2001,
		content = "屏蔽召唤物",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 0,
		platform = 2,
		order = 1120,
	},
	[2002] = { 
		id = 2002,
		content = "屏蔽特效",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 0,
		platform = 2,
		order = 1130,
	},
	[2003] = { 
		id = 2003,
		content = "屏蔽已方玩家",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 0,
		platform = 2,
		order = 1140,
	},
	[2004] = { 
		id = 2004,
		content = "屏蔽玩家",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 0,
		platform = 2,
		order = 1150,
	},
	[2005] = { 
		id = 2005,
		content = "屏蔽怪物",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 0,
		platform = 2,
		order = 1160,
	},
	[3000] = { 
		id = 3000,
		content = "生命值低于<font colorStyleID='1040006'>%s%%</font> 自动使用回城卷",
		text = "保护-回城",
		group = 5,
		group2 = 5,
		group_text = "保护设置",
		default = 0,
		platform = 0,
		order = 5000,
		default1 = 80,
	},
	[3001] = { 
		id = 3001,
		content = "生命值低于<font colorStyleID='1040006'>%s%%</font> 自动使用随机卷",
		text = "保护-随机",
		group = 5,
		group2 = 5,
		group_text = "保护设置",
		default = 0,
		platform = 0,
		order = 5500,
	},
	[3002] = { 
		id = 3002,
		content = "魔法值低于<font colorStyleID='1040006'>%s%%</font> 自动使用回城卷",
		text = "保护-回城",
		group = 5,
		group2 = 5,
		group_text = "保护设置",
		default = 0,
		platform = 0,
		order = 6000,
	},
	[3003] = { 
		id = 3003,
		content = "魔法值低于<font colorStyleID='1040006'>%s%%</font> 自动使用随机卷",
		text = "保护-随机",
		group = 5,
		group2 = 5,
		group_text = "保护设置",
		default = 0,
		platform = 0,
		order = 6500,
	},
	[3004] = { 
		id = 3004,
		content = "生命值低于<font colorStyleID='1040006'>%s%%</font> 自动使用红药HP",
		text = "普通恢复HP",
		group = 5,
		group2 = 5,
		group_text = "恢复设置",
		default = 1,
		platform = 0,
		order = 7000,
	},
	[3005] = { 
		id = 3005,
		content = "生命值低于<font colorStyleID='1040006'>%s%%</font> 自动使用瞬回药",
		text = "瞬回恢复HP",
		group = 5,
		group2 = 5,
		group_text = "恢复设置",
		default = 1,
		platform = 0,
		order = 7500,
	},
	[3006] = { 
		id = 3006,
		content = "魔法值低于<font colorStyleID='1040006'>%s%%</font> 自动使用蓝药MP",
		text = "普通恢复MP",
		group = 5,
		group2 = 5,
		group_text = "恢复设置",
		default = 1,
		platform = 0,
		order = 8000,
	},
	[3007] = { 
		id = 3007,
		content = "魔法值低于<font colorStyleID='1040006'>%s%%</font> 自动使用瞬回药",
		text = "瞬回恢复MP",
		group = 5,
		group2 = 5,
		group_text = "恢复设置",
		default = 1,
		platform = 0,
		order = 8500,
	},
	[3008] = { 
		id = 3008,
		content = "屏蔽英雄",
		text = "英雄设置",
		group = 5,
		group2 = 5,
		group_text = "英雄设置",
		default = 0,
		platform = 0,
		order = 9000,
	},
	[3009] = { 
		id = 3009,
		content = "合击震屏",
		text = "英雄设置",
		group = 5,
		group2 = 5,
		group_text = "英雄设置",
		default = 1,
		platform = 0,
		order = 9500,
	},
	[3010] = { 
		id = 3010,
		content = "自动合击",
		text = "英雄设置",
		group = 5,
		group2 = 5,
		group_text = "英雄设置",
		default = 0,
		platform = 0,
		order = 10000,
	},
	[3011] = { 
		id = 3011,
		content = "跟随主角攻击",
		text = "英雄设置",
		group = 5,
		group2 = 5,
		group_text = "英雄设置",
		default = 1,
		platform = 0,
		order = 10500,
	},
	[3012] = { 
		id = 3012,
		content = "英雄打怪物躲避",
		text = "英雄设置",
		group = 5,
		group2 = 5,
		group_text = "英雄设置",
		default = 1,
		platform = 0,
		order = 11000,
	},
	[3013] = { 
		id = 3013,
		content = "自动召唤英雄",
		text = "英雄设置",
		group = 5,
		group2 = 5,
		group_text = "英雄设置",
		default = 1,
		platform = 0,
		order = 11500,
	},
	[3014] = { 
		id = 3014,
		content = "英雄生命低于<font colorStyleID='1040006'>%s%%</font> 时自动收回",
		text = "保护-回城",
		group = 5,
		group2 = 5,
		group_text = "保护设置",
		default = 0,
		platform = 0,
		order = 8600,
		default1 = 50,
	},
	[3015] = { 
		id = 3015,
		content = "复活回城保护",
		text = "战斗",
		group = 3,
		group2 = 1,
		group_text = "综合",
		default = 0,
		platform = 0,
		order = 3750,
		tips = "复活戒指生效时，回城保护是否生效",
	},
}
return config
