local config = { 
	[1] = { 
		Idx = 1,
		name = "生命榜",
		nbvalue = "4680#14040#7020",
		type = 1,
		desc = "生命值",
		var = "C_QsQrolehp",
		time = 60,
		maxlist = 20,
	},
	[2] = { 
		Idx = 2,
		name = "战力榜",
		nbvalue = "11640#1838#3492",
		type = 1,
		desc = "攻击力",
		var = "C_QsQroleatt",
		time = 300,
		maxlist = 0,
	},
	[3] = { 
		Idx = 3,
		name = "击杀榜",
		nbvalue = "43200#1#1",
		type = 1,
		desc = "击杀数量",
		var = "C_QsQrolekiller",
		time = 120,
		maxlist = 50,
	},
	[4] = { 
		Idx = 4,
		name = "BOSS伤害",
		nbvalue = "43200#1#1",
		type = 2,
		desc = "DPS",
		var = "C_QsQdps",
		time = 1,
		maxlist = 5,
	},
	[5] = { 
		Idx = 5,
		name = "治疗量",
		nbvalue = "43200#1#1",
		type = 2,
		desc = "HEALS",
		var = "C_QsQheals",
		time = 1,
		maxlist = 5,
	},
	[6] = { 
		Idx = 6,
		name = "承受伤害",
		nbvalue = "43200#1#1",
		type = 2,
		desc = "TANK",
		var = "C_QsQtank",
		time = 1,
		maxlist = 5,
	},
}
return config
